In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
print("Rank of a: ", a.ndim)
print("Shape of a: ", a.shape)
print("Total number of elements in the array: ", a.size)
print("Data type of the elements of a:", a.dtype)

Rank of a:  1
Shape of a:  (3,)
Total number of elements in the array:  3
Data type of the elements of a: int64


In [7]:
b = np.array([[1., 2., 3.], [ 4., 5., 6.]])

print("Rank of b: ", b.ndim)
print("Shape of b: ", b.shape)
print("Total number of elements in b: ", b.size)
print("Data type of the elements of b:", b.dtype)

Rank of b:  2
Shape of b:  (2, 3)
Total number of elements in b:  6
Data type of the elements of b: float64


### Array Creation

In [12]:
a = np.zeros((3,3))
print(a)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [13]:
a = np.ones((2,5))
print(a)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [14]:
c = np.zeros_like(a)
c

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [15]:
c = np.ones_like(b)
c

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [17]:
d = np.full((2,2), 7)
print(d)

[[7 7]
 [7 7]]


In [18]:
e = np.eye(3)
print(e)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [19]:
f = np.random.random((2,2))
print(f)

[[ 0.54128037  0.9537103 ]
 [ 0.25064897  0.69787876]]


In [24]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [30]:
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

### Array indexing

In [32]:
a = np.linspace(0, 500, 6)
print(a)

[   0.  100.  200.  300.  400.  500.]


In [33]:
a[2:4]

array([ 200.,  300.])

In [2]:
a = np.array([
    np.linspace(1, 3, 3),
    np.linspace(4, 6, 3),
    np.linspace(7, 9, 3)
])
print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [46]:
a[0,0]

1.0

In [47]:
a[0]

array([ 1.,  2.,  3.])

In [49]:
a[:2, 1:]

array([[ 2.,  3.],
       [ 5.,  6.]])

In [50]:
a[1:, 1:]

array([[ 5.,  6.],
       [ 8.,  9.]])

In [4]:
a = np.array([
    [1,2],[3,4],[5,6]
])
bool_idx = (a > 2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [52]:
print(a[bool_idx])

[3 4 5 6]


In [53]:
print(a[a > 2])

[3 4 5 6]


### Other function to subset an array

**where**

In [9]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
np.where(a > 2)

AttributeError: 'tuple' object has no attribute 'T'

In [55]:
print(a, "\n")
m, n = np.where(a > 2)
print("Axis-0: ", m)
print("Axis-1: ",n)

[[1 2]
 [3 4]
 [5 6]] 

Axis-0:  [1 1 2 2]
Axis-1:  [0 1 0 1]


In [56]:
a[m, n]

array([3, 4, 5, 6])

**diag**

In [57]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
print(A, '\n')
print(np.diag(A))

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]] 

[ 0 11 22 33 44]


**reverse diagonal**

In [59]:
A[:, ::-1]

array([[ 4,  3,  2,  1,  0],
       [14, 13, 12, 11, 10],
       [24, 23, 22, 21, 20],
       [34, 33, 32, 31, 30],
       [44, 43, 42, 41, 40]])

In [60]:
np.diag(A[:, ::-1])

array([ 4, 13, 22, 31, 40])

**Take, indexing via a list**

In [62]:
v = np.arange(-3,3)
v

array([-3, -2, -1,  0,  1,  2])

In [63]:
row_idx = [1, 3, 5]
v[row_idx]

array([-2,  0,  2])

In [64]:
np.take([-3, -2, -1, 0, 1, 2], row_idx)

array([-2,  0,  2])

### Linear Algebra
**Elementwise-array operations¶**

In [65]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y, '\n')
print(np.add(x, y))

[[  6.   8.]
 [ 10.  12.]] 

[[  6.   8.]
 [ 10.  12.]]


In [67]:
print(x - y, '\n')
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]] 

[[-4. -4.]
 [-4. -4.]]


In [68]:
print(x * y, '\n')
print(np.multiply(x, y))

[[  5.  12.]
 [ 21.  32.]] 

[[  5.  12.]
 [ 21.  32.]]


In [69]:
print(x / y, '\n')
print(np.divide(x, y))

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]] 

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [70]:
print(a**2, '\n')
print(np.square(a))

[[ 1  4]
 [ 9 16]
 [25 36]] 

[[ 1  4]
 [ 9 16]
 [25 36]]


In [71]:
np.exp(a)

array([[   2.71828183,    7.3890561 ],
       [  20.08553692,   54.59815003],
       [ 148.4131591 ,  403.42879349]])

In [74]:
print(a**1.2, '\n')
print(np.power(a, 1.2))

[[ 1.          2.29739671]
 [ 3.73719282  5.27803164]
 [ 6.89864831  8.58581449]] 

[[ 1.          2.29739671]
 [ 3.73719282  5.27803164]
 [ 6.89864831  8.58581449]]


In [78]:
print("Natural logarithm: \n", np.log(a))
print("\nBase10 logarithm: \n", np.log10(a))
print("\nBase2 logarithm: \n", np.log2(a))

Natural logarithm: 
 [[ 0.          0.69314718]
 [ 1.09861229  1.38629436]
 [ 1.60943791  1.79175947]]

Base10 logarithm: 
 [[ 0.          0.30103   ]
 [ 0.47712125  0.60205999]
 [ 0.69897     0.77815125]]

Base2 logarithm: 
 [[ 0.          1.        ]
 [ 1.5849625   2.        ]
 [ 2.32192809  2.5849625 ]]


### Vector Operations

In [79]:
v1 = np.arange(0, 5)
v1

array([0, 1, 2, 3, 4])

In [80]:
print(v1 * 2)
print(v1 / 2)
print(v1 ** 2)
print(v1 * v1)

[0 2 4 6 8]
[ 0.   0.5  1.   1.5  2. ]
[ 0  1  4  9 16]
[ 0  1  4  9 16]


**Inner product**

In [82]:
v1 = [0, 1, 2, 3, 4]
v2 = [5, 6, 7, 8, 9]

np.dot(v1, v2)

80

**Vector Magnitude (self inner product)**

In [85]:
summ = 0
for element in v1:
    summ += element * element
summ

30

In [87]:
np.sum([element*element for element in v1])

30

In [101]:
v1 = np.array([0, 1, 2, 3, 4])
v1@v1

30

### Matrix Algebra

In [92]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [93]:
A.T

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44]])

**Matrix-Vector Multiplication**

In [94]:
v1

[0, 1, 2, 3, 4]

In [102]:
# v1 is multiplied to each row
A * v1

array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

In [103]:
# Elementwise Matrix Multiplication
A * A

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [105]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [104]:
# Matrix Multiplication
A.dot(A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [100]:
A@A

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

Alternatively we can cast the array to Matrix , which enables normal arithmatic opertions to perform matrix algebra.

In [112]:
A_mat = np.matrix(A)
v = np.matrix(v1).T
print("Matrix A:\n", A_mat)
print("\nVector v:\n", v) # make it a column vector

Matrix A:
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]

Vector v:
 [[0]
 [1]
 [2]
 [3]
 [4]]


In [113]:
type(A_mat)

numpy.matrixlib.defmatrix.matrix

In [114]:
A_mat * A_mat

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [116]:
v.T * A_mat

matrix([[300, 310, 320, 330, 340]])

In [118]:
A_mat * v

matrix([[ 30],
        [130],
        [230],
        [330],
        [430]])

**Other Useful Functions**

In [119]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [120]:
A.sum()

550

In [121]:
# column-wise
A.sum(axis=0)

array([100, 105, 110, 115, 120])

In [122]:
# row-wise
A.sum(axis=1)

array([ 10,  60, 110, 160, 210])

**Statistics**

In [123]:
print("Mean of A: \n", A.mean())
print("Column-wise mean of A: \n", A.mean(axis=0))
print("Row-wise mean of A: \n", A.mean(axis=1))

Mean of A: 
 22.0
Column-wise mean of A: 
 [ 20.  21.  22.  23.  24.]
Row-wise mean of A: 
 [  2.  12.  22.  32.  42.]


In [124]:
# Variance
print("Variance of A: \n", A.var())
print("Column-wise variance of A: \n", A.var(axis=0))
print("Row-wise variance of A: \n", A.var(axis=1))

Variance of A: 
 202.0
Column-wise variance of A: 
 [ 200.  200.  200.  200.  200.]
Row-wise variance of A: 
 [ 2.  2.  2.  2.  2.]


In [125]:
# Standard deviation
print("Standard Deviation of A: \n", A.std())
print("Column-wise Standard Deviation of A: \n", A.std(axis=0))
print("Row-wise Standard Deviation of A: \n", A.std(axis=1))

Standard Deviation of A: 
 14.2126704036
Column-wise Standard Deviation of A: 
 [ 14.14213562  14.14213562  14.14213562  14.14213562  14.14213562]
Row-wise Standard Deviation of A: 
 [ 1.41421356  1.41421356  1.41421356  1.41421356  1.41421356]


In [126]:
#Min and Max
print("Minimum of A: \n", A.min())
print("Column-wise Minimum of A: \n", A.min(axis=0))
print("Row-wise Minimum of A: \n", A.min(axis=1))
print("Maximum of A: \n", A.max())
print("Column-wise Maximum of A: \n", A.max(axis=0))
print("Row-wise Maximum of A: \n", A.max(axis=1))

Minimum of A: 
 0
Column-wise Minimum of A: 
 [0 1 2 3 4]
Row-wise Minimum of A: 
 [ 0 10 20 30 40]
Maximum of A: 
 44
Column-wise Maximum of A: 
 [40 41 42 43 44]
Row-wise Maximum of A: 
 [ 4 14 24 34 44]


### Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations

In [127]:
X = np.array([[1,2],[3, 4] ,[5,6], [7,8]])
v = np.array([1, 2])
print("X: \n", X)
print("\nv:\n", v)

X: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

v:
 [1 2]


We can add the vector v to each row of the matrix x, storing the result in the matrix y

In [128]:
Y = np.zeros_like(X)
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    Y[i, :] = X[i, :] + v
print(Y)

[[ 2  4]
 [ 4  6]
 [ 6  8]
 [ 8 10]]


Adding v to every row of matrix X is equivalent to form a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of X and vv

In [129]:
vv = np.tile(v, (4,1)) # stack four rows of v
print("Stacked vectors: \n", vv)
Y = X + vv # Add x and vv elementwise
print("\nResult: \n", Y)

Stacked vectors: 
 [[1 2]
 [1 2]
 [1 2]
 [1 2]]

Result: 
 [[ 2  4]
 [ 4  6]
 [ 6  8]
 [ 8 10]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v . Subject to certain constraints, the smaller array is broadcast across the larger array so that they have compatible shapes.

In [131]:
Y = X + v # Add v to each row of x using broadcasting
print(Y)

[[ 2  4]
 [ 4  6]
 [ 6  8]
 [ 8 10]]


Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

In [132]:
v = np.array([1])
print("Rank of v: ", v.ndim)
print(v, '\n')
print(X)

Rank of v:  1
[1] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [134]:
print(X + v)

[[2 3]
 [4 5]
 [6 7]
 [8 9]]


Compute outer product of vectors

In [135]:
v = np.array([1,2,3]) # v has shape (3,)
w = np.array([4,5]) # w has shape (2,)
np.reshape(v, (3, 1))

array([[1],
       [2],
       [3]])

In [136]:
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


### Array Reshape, Concatenation, Stacking and Copy

**Reshape**

In [152]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
print(A.shape)
print(A)

(5, 5)
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


In [156]:
m, n = A.shape
B = A.reshape((1, m*n))
print(B.shape)
print(B)

(1, 25)
[[ 0  1  2  3  4 10 11 12 13 14 20 21 22 23 24 30 31 32 33 34 40 41 42 43
  44]]


In [157]:
B[0, :5] = -1
B

array([[-1, -1, -1, -1, -1, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
        32, 33, 34, 40, 41, 42, 43, 44]])

In [158]:
A

array([[-1, -1, -1, -1, -1],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [159]:
B = A.flatten()
print(B.shape)
print(B)

(25,)
[-1 -1 -1 -1 -1 10 11 12 13 14 20 21 22 23 24 30 31 32 33 34 40 41 42 43 44]


In [160]:
B[0:5] = 10
B

array([10, 10, 10, 10, 10, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [161]:
A

array([[-1, -1, -1, -1, -1],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

**Concatenation and Stacking**

Join a sequence of arrays along an existing axis

In [164]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(a, '\n')
print(b)

[[1 2]
 [3 4]] 

[[5 6]]


In [165]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [168]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [169]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [171]:
np.hstack((a, b.T))

array([[1, 2, 5],
       [3, 4, 6]])

**Copy**

To achieve high performance, assignments in Python usually do not copy the underlaying objects. This is important for example when objects are passed between functions, to avoid an excessive amount of memory copying when it is not necessary (technical term: pass by reference).

In [172]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [174]:
# now B is referring to the same array data as A
B = A
# changing B affects A
B[0,0] = 10
A

array([[10,  2],
       [ 3,  4]])

If we want to avoid this behavior, so that when we get a new completely independent object B copied from A , then we need to do a so-called “deep copy” using the function copy

In [176]:
B = A.copy()
B[0, 0] = -5
A

array([[10,  2],
       [ 3,  4]])